config/routes.rb
Rails.application.routes.draw do

  # Ruta del monitoreo
  root 'main#index'

  resources :players

  # Ruta para Administrar el inicio y el fin de las rondas
  get '/admin_game', to: 'main#admin_game'

  # Ruta para ejecutar el Thread del juego
  post '/play_game', to: 'main#play_game'

  # Ruta para detener el Thread del juego
  post '/stop_game', to: 'main#stop_game'

  # Serve websocket ActionCable
  mount ActionCable.server => '/cable'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bet_history.rb
class BetHistory < ApplicationRecord
  belongs_to :player
  after_create :send_to_action_cable

  # Se incluye archivo random_color.rb (Concerns) que contiene funcion de random_color 
  include RandomColor

  # Funcion que crea BetHistory que se va a mostrar en el monitoreo
  def self.create_bet_histories players, color_roulette

  	players.each do |player|

	  	bet_history = BetHistory.new(player_id: player.id, 
	  								 date: Time.now, 
	  								 color_player: player.current_color,
	  								 bet_player: player.current_bet,
	  								 color_roulette: color_roulette,
	  								 result: player.current_result)
	  	bet_history.save

  	end

  end

  # Funcion que retorna todo los BetHistory con el nombre completo del jugador
  def self.find_all_with_full_name

    BetHistory.select("(players.name || ' ' || players.last_name) as name, date, color_player, bet_player, color_roulette, result")
               .joins(:player)
               .order("date DESC")

  end

  # Funcion que retorna el nombre completo del jugador
  def full_name
    self.player.name + " " + self.player.last_name
  end

  private

    # Funcion que envia al canal del ActionCable llamado "bet_history" el html renderizado  
    def send_to_action_cable
      ActionCable.server.broadcast "bet_history", to_html
    end

    # Renderiza y retorna el HTML de la vista _bet_history con el nuevo registro ingresado
    def to_html
      ApplicationController.renderer.render(partial: 'bet_histories/bet_history', locals: { bet_history: self })
    end

end

app/models/concerns/random_color.rb
module RandomColor
	extend ActiveSupport::Concern

	module ClassMethods

		# Funcion que retorna un string en base a un random
		# 1 a 2 de 100 (2%) = Verde
		# 3 a 51 de 100 (49%) = Rojo 
		# 52 a 100 de 100 (49%) = Negro  
		def random_color

			color = "Verde"

			case rand(1..100)
				when 3..51
					color = "Rojo"
				when 52..100
					color = "Negro"
			end

			return color

		end
	end
end

app/models/player.rb
class Player < ApplicationRecord

	# Se incluye archivo random_color.rb (Concerns) que contiene funcion de color_random 
	include RandomColor

	# Consulta que busca los jugadores que tienen dinero para apostar
	scope :players_with_cash, -> { where("cash > ?", 0) }


	# Funcion que valida si ya se consumio la API del Clima, busca los jugadores que pueden apostar
	# y realiza las apuestas de los Players
	def self.bet_players color_roulette
	  	
	  	players = Player.players_with_cash

		players.map { |player|

			current_bet_player(player)
			update_cash_and_current_result(player, color_roulette)

		}

		return players

	end

  	# Funcion que modifica Player con su Apuesta Actual
  	def self.current_bet_player player

  		# Si es menor a $1.000 el Player va All in
  		if player.cash <= 1000
  			player.current_bet = player.cash
  		else
  			player.current_bet = random_bet_cash_player(player.cash)
  		end

  		player.current_color = random_color

  	end

  	# Funcion que retorna la cantidad de dinero que el Player apuesta en base al Clima
  	def self.random_bet_cash_player cash_player

		if $weather
  			return ((cash_player * rand(4..10)) / 100).to_i
		end

  		return ((cash_player * rand(8..15)) / 100).to_i

  	end


	# Funcion que Actualiza la cantidad de dinero y apuesta actual del Player
	def self.update_cash_and_current_result player, color_roulette

		player.current_result = result_bet(player, color_roulette)
		player.cash += player.current_result
		player.save

	end

	# Funcion que obtiene el resultado de la apuesta en dinero
	def self.result_bet player, color_roulette

		if player.current_color == color_roulette

			case color_roulette
				when 'Verde'
					return player.current_bet * 15
				else
					return player.current_bet * 2
			end

		end

		return player.current_bet * -1

	end

  	# Funcion que retorna True si en el pronostico de los siguiente 7 dias hay temperaturas
  	# sobre los 32 Grados
  	def self.weather_more_than_thirty_two

  		api_weather.take(7).each do |forecastday|
	
			if (forecastday["high"]["celsius"]).to_i > 32
				return true
			end

		end

		return false

  	end

  	# Funcion que realiza el consumo de la API y retorna el JSON con el pronostico 
  	def self.api_weather

		api_key = "047364c18d25895e"
		url_api = "http://api.wunderground.com/api/#{api_key}/forecast10day/lang:SP/q/CL/Santiago.json"
		json_api = HTTParty.get(url_api)
		return json_api["forecast"]["simpleforecast"]["forecastday"]

  	end

  	# Funcion que agrega $10.000 a todos los jugadores
  	def self.end_of_the_day

  		Player.all.map { |player| 
  			player.cash += 10000
  			player.save
  		}

  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  @@thread = Thread.new { }
	
  # GET /
  def index
    @bet_histories = BetHistory.find_all_with_full_name
  end

  # POST /play_game
  def play_game
    
    unless @@thread.alive?
      $weather = Player.weather_more_than_thirty_two 
      @@thread = Thread.new { play_game_thread }
    end
    redirect_to root_path

  end

  # GET /admin_game
  def admin_game
  end

  # POST /stop_game
  def stop_game

  	if @@thread.alive?
      Player.end_of_the_day
  		@@thread.exit
  	end
    redirect_to root_path

  end

  # Funcion que contiene un bucle para que se ejecute cada 3 min las apuestas
  def play_game_thread

  	while true
  		color_roulette = BetHistory.random_color
  		players = Player.bet_players(color_roulette)
  		BetHistory.create_bet_histories(players, color_roulette)
  		sleep(180)  	
  	end

  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    # Inicio Cash 10.000
    @player.cash = 10000

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :last_name, :cash, :current_color, :current_bet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/bet_histories/_bet_history.html.erb
<tr>
	<td><%= bet_history.try(:name) || bet_history.full_name %></td>
	<td class="text-center"><%= bet_history.date.strftime("%d-%m-%Y %H:%M:%S") %></td>
	<td class="<%= bet_history.color_player %>"></td>
	<td class="text-center"><%= bet_history.bet_player %></td>
	<td class="<%= bet_history.color_roulette %>"></td>
	<td class="text-center <%= bet_history.result >= 0 ? 'positivo' : 'negativo' %>"><%= bet_history.result %></td>
</tr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>TareaNnodes</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
			<a class="navbar-brand">TareaNnodes</a>
			</div>
			<ul class="nav navbar-nav">
				<li><%= link_to "Monitoreo", "/"%></li>
				<li><%= link_to "Adminitración", "/admin_game"%></li>
				<li><%= link_to "Jugadores", "players"%></li>
			</ul>
		</div>
	</nav>
	<div class="container principal">
		<%= yield %>
	</div>
</body>
</html>

app/views/main/admin_game.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Inicio y Fin de las Rondas</h1>

<div class="row">
	<div class="col-xs-6">
		<%= link_to "Comenzar el día", "/play_game", method: :post, class: :"btn btn-success btn-lg" %> <br>
	</div>
	<div class="col-xs-6">
		<%= link_to "Fin del día", "/stop_game", method: :post, class: :"btn btn-warning btn-lg" %> <br>
	</div>
</div>

</table>

app/views/main/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Monitoreo</h1>

<div class="progress">
  <div class="progress-bar progress-bar-info progress-bar-striped" id="time" role="progressbar" aria-valuenow="180" aria-valuemin="0" aria-valuemax="100">
  </div>
</div>

<table class="table table-hover">
  <thead>
    <tr class="text-center-tr">
      <th>Jugador</th>
      <th>Fecha</th>
      <th>Color Jugador</th>
      <th>Apuesta Jugador</th>
      <th>Color Ruleta</th>
      <th>Resultado</th>
    </tr>
  </thead>

  <tbody id="bet_histories">
    <%= render @bet_histories %>
  </tbody>

</table>

app/views/players/_form.html.erb
<%= form_for(player) do |f| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name, 'Nombre'%>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :last_name, 'Apellido' %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :cash, 'Dinero' unless @player.new_record? %>
    <%= f.number_field :cash, class: "form-control" unless @player.new_record? %>
  </div>

  <div class="actions">
    <%= f.submit (@player.new_record? ? 'Crear Jugador' : 'Editar Jugador'), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editar Jugador</h1>

<%= render 'form', player: @player %>

<%= link_to 'Ver', @player %> |
<%= link_to 'Volver', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Jugadores</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Dinero</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.last_name %></td>
        <td><%= player.cash %></td>
        <td><%= link_to 'Editar', edit_player_path(player) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Jugador', new_player_path, class: "btn btn-primary" %>

app/views/players/new.html.erb
<h1>Nuevo Jugador</h1>

<%= render 'form', player: @player %>

<%= link_to '< Volver', players_path, class: "volver" %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @player.last_name %>
</p>

<p>
  <strong>Dinero:</strong>
  <%= @player.cash %>
</p>

<%= link_to 'Editar', edit_player_path(@player) %> |
<%= link_to 'Volver', players_path %>